services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - PORT=3000
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - backend-network

  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:9.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - '127.0.0.1:5050:80'
    networks:
      - backend-network
    depends_on:
      - postgres

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --protocol http2 --no-autoupdate --loglevel debug run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - backend-network
    depends_on:
      - backend

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend-network:
    driver: bridge
