services:
  app:
    container_name: app
    build: ./backend
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - app-network

  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:2025.4.2
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
